"""Sample/seed dispatches. Not live reporting — used by the 'sample' provider
and mirrored on the frontend as an offline fallback."""

SEED = [
    {"id": "1",  "cat": "politics",    "scope": "national",      "src": "Capital Ledger",   "min": 14,  "read": 6, "title": "Parliament passes revised data-protection bill after marathon session", "dek": "The amended framework tightens consent rules and creates an independent oversight board, though enforcement timelines remain contested."},
    {"id": "2",  "cat": "economy",     "scope": "international",  "src": "Globe Wire",       "min": 41,  "read": 5, "title": "Central banks signal a slower path on rate cuts as inflation cools unevenly", "dek": "Policymakers across three continents struck a cautious tone, wary that easing too quickly could reignite price pressures."},
    {"id": "3",  "cat": "technology",  "scope": "international",  "src": "Frontier Desk",    "min": 58,  "read": 4, "title": "Open-source models close the gap with proprietary systems on key benchmarks", "dek": "A new wave of community-trained models is shifting how startups think about cost, control, and deployment."},
    {"id": "4",  "cat": "society",     "scope": "national",      "src": "Civic Daily",      "min": 95,  "read": 7, "title": "Cities pilot four-day work weeks, and early data looks surprisingly good", "dek": "Productivity held steady while reported burnout dropped sharply across the trial cohorts."},
    {"id": "5",  "cat": "culture",     "scope": "national",      "src": "The Meridian",     "min": 130, "read": 5, "title": "Independent bookshops report their strongest year in over a decade", "dek": "Curated shelves and community events are pulling readers back from the algorithmic feed."},
    {"id": "6",  "cat": "environment", "scope": "international",  "src": "Atlas Report",     "min": 165, "read": 8, "title": "Record investment in grid-scale storage reshapes the renewables math", "dek": "Falling battery costs are making round-the-clock clean power viable in regions that once relied on gas."},
    {"id": "7",  "cat": "health",      "scope": "national",      "src": "Harbor Review",    "min": 190, "read": 6, "title": "Public clinics expand mental-health screening into routine checkups", "dek": "Early-detection programs aim to catch conditions before they escalate, but staffing remains the bottleneck."},
    {"id": "8",  "cat": "science",     "scope": "international",  "src": "Northline",        "min": 220, "read": 9, "title": "Astronomers map a faint galaxy that predates most known structures", "dek": "The find pushes back the timeline for early galaxy formation and raises fresh questions for cosmologists."},
    {"id": "9",  "cat": "economy",     "scope": "national",      "src": "The Standard",     "min": 260, "read": 4, "title": "Small-business lending rebounds as regional banks loosen terms", "dek": "Owners cite easier access to working capital, though many remain cautious about expansion."},
    {"id": "10", "cat": "sports",      "scope": "international",  "src": "Continental Post", "min": 300, "read": 3, "title": "Underdog squad stuns the title favorites in a late-game collapse", "dek": "A disciplined defensive game plan undid a side that had not lost at home all season."},
    {"id": "11", "cat": "technology",  "scope": "national",      "src": "Frontier Desk",    "min": 340, "read": 5, "title": "Regulators draft first rules for autonomous delivery on city streets", "dek": "The proposal balances safety testing with a path for operators to scale pilots responsibly."},
    {"id": "12", "cat": "politics",    "scope": "international",  "src": "Globe Wire",       "min": 380, "read": 6, "title": "Regional bloc reaches a tentative deal on migration and border funding", "dek": "Negotiators called it a fragile compromise that still needs ratification from member states."},
    {"id": "13", "cat": "culture",     "scope": "international",  "src": "The Meridian",     "min": 430, "read": 5, "title": "A restored silent-era film finds a new audience at festivals worldwide", "dek": "Painstaking digital work brought a century-old print back to vivid, flickering life."},
    {"id": "14", "cat": "society",     "scope": "international",  "src": "Atlas Report",     "min": 500, "read": 7, "title": "Volunteer networks step in as housing pressure reshapes mid-size towns", "dek": "Mutual-aid groups are filling gaps that strained municipal services can no longer cover alone."},
    {"id": "15", "cat": "environment", "scope": "national",      "src": "Harbor Review",    "min": 560, "read": 6, "title": "Coastal wetlands restoration pays off with measurable flood protection", "dek": "Restored marshland is absorbing storm surge that once reached low-lying neighborhoods."},
    {"id": "16", "cat": "health",      "scope": "international",  "src": "Northline",        "min": 620, "read": 8, "title": "A long-running study links sleep regularity to long-term heart health", "dek": "Consistency of sleep timing mattered as much as total hours, researchers found."},
    {"id": "17", "cat": "science",     "scope": "national",      "src": "The Standard",     "min": 700, "read": 5, "title": "University lab turns farm waste into a low-cost building material", "dek": "The composite is strong, fire-resistant, and cheaper than conventional alternatives in early trials."},
    {"id": "18", "cat": "economy",     "scope": "international",  "src": "Continental Post", "min": 780, "read": 4, "title": "Shipping costs ease as new routes relieve a year of port congestion", "dek": "Importers expect the relief to filter through to consumer prices over the coming months."},
    {"id": "19", "cat": "technology",  "scope": "international",  "src": "Frontier Desk",    "min": 880, "read": 6, "title": "Privacy-first search tools gain ground among mainstream users", "dek": "Frustration with tracking is nudging everyday users toward alternatives once seen as niche."},
    {"id": "20", "cat": "sports",      "scope": "national",      "src": "Civic Daily",      "min": 960, "read": 3, "title": "Grassroots leagues report record sign-ups after a new funding push", "dek": "Investment in local pitches and coaching is widening access for younger players."},
]
